# expect: constraint
# every step on its own line: far too many lines
pawn.move()
pawn.move()
pawn.move()
pawn.turn_left()
pawn.move()
pawn.move()
pawn.turn_left()
pawn.move()
pawn.move()
pawn.turn_right()
pawn.move()
pawn.move()
pawn.move()
pawn.turn_right()
pawn.move()
pawn.move()
pawn.move()
pawn.move()
