# expect: constraint
pawn.turn_right()
pawn.move(7)
pawn.turn_right()
pawn.move(6)
pawn.turn_right()
pawn.move(5)
pawn.turn_right()
pawn.move(4)
pawn.turn_right()
pawn.move(3)
pawn.turn_right()
pawn.move(2)
pawn.turn_right()
pawn.move()
